### ISSUE TITLE
Couple of Rooms.. 

### ISSUE THREAD

**Issue by Brebinator** [stom66/warframe-dojo-planner#2]
Hey there, 

Thanks so much for the tool. definitely useful. I noted that the custom obstacle course and the inspirational rooms are not part of the misc assets. Should I just amend this or did you have assets already for them as I wanted to keep it all consistent and didn't wish to duplicate items that may be already done. 

Thank you again. The dry dock really helped...

**Comment by stom66** [comment]
Apologies for not spotting this sooner. I don't have the assets for them so feel free to add them if you have them! Thanks.

**Comment by stom66** [comment]
These assets have been added by lukepot. Many thanks to him for updating the project.
