### ISSUE TITLE
Missing Rooms

### ISSUE THREAD

**Issue by HAMBRUGNATCHERS** [stom66/warframe-dojo-planner#3]
There are a few missing rooms that appear on the wiki but are not in the website. Also, I have no knowledge of using JavaScript, CSS, or HTML. I would like to build this in swift playgrounds for iPad, but I don’t even know where to start. If you could explain how to do this, please use “dum dum” terms. I know this is the wrong place for this, but I didn’t know where else to put this.

**Comment by stom66** [comment]
I no longer play the game I'm afraid, and I've never heard of playgrounds.
